version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: truffle
    versions:
    - 5.1.63
    - 5.1.64
    - 5.1.65
    - 5.1.66
    - 5.1.67
    - 5.2.1
    - 5.2.2
    - 5.2.3
    - 5.2.4
    - 5.2.5
    - 5.2.6
    - 5.3.0
    - 5.3.1
    - 5.3.2
  - dependency-name: prettier-plugin-solidity
    versions:
    - 1.0.0-beta.3
    - 1.0.0-beta.4
    - 1.0.0-beta.5
    - 1.0.0-beta.6
    - 1.0.0-beta.7
    - 1.0.0-beta.8
    - 1.0.0-beta.9
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: solhint
    versions:
    - 3.3.2
    - 3.3.3
  - dependency-name: "@openzeppelin/contracts"
    versions:
    - 3.3.0
    - 3.4.0
    - 3.4.1
  - dependency-name: lodash
    versions:
    - 4.17.20
