sudo: required
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '12.13.1'
deploy:	
  provider: pages	
  skip_cleanup: true	
  github_token: $GITHUB_TOKEN	
  keep_history: true	
  local_dir: docs
  on:	
    branch: master	
  target_branch: master
env:
  - TASK=lint:tests
  - TASK=lint:contracts
  - TASK=test
before_script:
  - npm run generate:doc
  - npm run ganache-ci
  - sleep 5
script:
  - travis_wait 60 npm run $TASK
#after_success:
#  - npm run coverage && cat coverage/lcov.info | coveralls
